clear
############################### Colors #################################################
lightblue=`tput setaf 14` 
green=`tput setaf 46`     
RED=`tput setaf 196` 
red=`tput setaf 196`     
yellow=`tput setaf 11`    
purple=`tput setaf 129`   
reset=`tput sgr0`  
############################### Options Menu ############################################   
printf "\e[1;92m Tool requires are installing!\n\e[0m" && sleep 1
apt-get -y install tor &> /dev/null || exit 1
apt-get install curl -y &> /dev/null || exit 1
make install &> /dev/null || exit 1
printf "\e[1;92m All Requires are installed!\n\e[0m" sleep 2
echo "${green}
             __               
  |  | |__| /  \  /\   |\/| |  
  |/\| |  | \__/ /~~\  |  | |  
                              
    Take back your privacy 
        Android verion

 [1] Start Whoami 
 [2] Stop Whoami 
 [3] Restart Whoami  "
echo -n "${green}
 > ${reset}" && read option
############################### Start Whoami ############################################# 
if [[ $option == "1" ]]; then
printf "\e[1;92m Whoami Starting!\n\e[0m" && sleep 2
echo -n "${yellow} * DNS changing" && sleep 2 
if service network-manager stop 
echo "# Generated by Whoami android version 
nameserver 84.200.69.80
nameserver 84.200.70.40
nameserver 91.239.100.100
# NOTE: the libc resolver may not support more than 3 nameserver.
# The nameserver listed below may not be recognized.
nameserver 89.233.43.71
nameserver 192.168.1.1" > /etc/resolv.conf 
service network-manager start ; then
 echo "${green} [OK]" 
else echo  "${RED} [FAIL]" && exit 1
fi
echo -n "${purple} * TOR starting"
if bash Tproxy.sh -t > /dev/null ; then
    echo "${green} [OK]"
else echo  "${RED} [FAIL]" && exit 1
fi
echo -n "${RED} * Your Whoami ip :" && echo -n "${green} "   &&  curl icanhazip.com 2> /dev/null 
############################### Stop Whoami ##############################################
elif [[ $option == "2" ]]; then 
printf "\e[1;92m Whoami Stopping!\n\e[0m" && sleep 2
a=$(pwd)
echo -n "${yellow} * Dns setting are set default" && sleep 2 
if service network-manager stop
cd /etc
chattr -i resolv.conf > /dev/null
rm -fr resolv.conf  
service network-manager start ; then
    echo "${green} [OK]" 
else echo  "${RED} [FAIL]" && exit 1
fi
echo -n "${purple} * TOR stopting"
cd $a 
if bash Tproxy.sh -c > /dev/null && service network-manager restart ; then
    echo "${green} [OK]" 
else echo  "${RED} [FAIL]" && exit 1
fi
echo -n "${RED} * Your current ip :" && echo -n "${green} "   &&  curl icanhazip.com 2> /dev/null 
############################# Restart Whoami ##############################################
elif [[ $option == "3" ]]; then 
printf "\e[1;92m Whoami Restarting!\n\e[0m" && sleep 1
a=$(pwd)  
echo -n "${yellow} * DNS changing" && sleep 2 
cd /etc
chattr -i resolv.conf > /dev/null
if service network-manager stop 
echo "# Generated by Whoami android version 
nameserver 84.200.69.80
nameserver 84.200.70.40
nameserver 91.239.100.100
# NOTE: the libc resolver may not support more than 3 nameserver.
# The nameserver listed below may not be recognized.
nameserver 89.233.43.71
nameserver 192.168.1.1" > /etc/resolv.conf 
service network-manager start ; then
 echo "${green} [OK]" 
else echo  "${RED} [FAIL]" && exit 1
fi
cd $a
echo -n "${purple} * TOR restarting"
if bash Tproxy.sh -c > /dev/null && bash Tproxy.sh -t > /dev/null ; then
    echo "${green} [OK]" 
else echo  "${RED} [FAIL]" && exit 1
fi
echo -n "${RED} * Your Whoami ip :" && echo -n "${green} "   &&  curl icanhazip.com 2> /dev/null 
fi
